DEFAULT archlinuxarm
TIMEOUT 50
MENU TITLE Orange Pi 5 Plus

LABEL archlinuxarm
    MENU LABEL Arch Linux ARM 6.18.50
    LINUX /boot/Image-orangepi5plus
    FDT /boot/dtbs/orangepi5plus/rockchip/rk3588-orangepi-5-plus.dtb
    APPEND root=PARTUUID=93b3f00d-5c7b-4ed7-9c2f-d9e93b995c01 rootwait rw console=tty1 console=ttyS2,1500000n8 earlycon=uart8250,mmio32,0xfeb50000

